FROM php:8.3-fpm

RUN apt-get update && apt-get install -y \
    git curl zip unzip

COPY . /app
WORKDIR /app

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN composer install --no-dev --optimize-autoloader